//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class book_tbl
    {
        public string book_id { get; set; }
        public string book_name { get; set; }
        public string book_genre { get; set; }
        public string author_name { get; set; }
        public string publisher_name { get; set; }
        public string book_language { get; set; }
        public string book_edition { get; set; }
        public string book_quantity { get; set; }
    }
}
