//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class member_tbl
    {
        public string member_id { get; set; }
        public string full_name { get; set; }
        public string email { get; set; }
        public string birthdate { get; set; }
        public string state { get; set; }
        public string city { get; set; }
        public string zipcode { get; set; }
        public string address { get; set; }
        public string password { get; set; }
        public string phone_number { get; set; }
    }
}
